### ISSUE TITLE
bash code is full of 'type -P' calls without error handling

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#104]
Specific case I've seen:

```
__filter_env() {
    local opts
    [[ ${PKGCORE_DEBUG} -ge 1 ]] && opts="--debug"
    PYTHONPATH="${PKGCORE_PYTHONPATH}" "${PKGCORE_PYTHON_BINARY}" \
        $(type -P filter-env) ${opts} "$@" || die "filter-env invocation failed"
}
```

Here if bash can't find `filter-env`, it spawns `python -f ...`. But if you look through the file, you'll see a lot of `type -P` calls assuming no possibility of failure.

**Comment by radhermit** [comment]
I'm only finding about 3, most have checks from what I can see.

**Comment by radhermit** [comment]
Fixed those three, if you find other examples where it's not checking post them here and reopen if you like.

**Comment by ferringb** [comment]
...Offhand, those type -P invocations that lack error checking are using pkgcore internals.  If they're missing, a fuck ton of other things will be breaking long before getting to this specific failure.

@Radhermit: I'd suggest just adding a function that does the appropriate lookup || die, rather than introducing local assignments (which may or may not get dumped out via env saving if invoked in the wrong spots).

**Comment by radhermit** [comment]
On 2015-08-03 01:47, ferringb wrote:
> ...Offhand, those type -P invocations that lack error checking are
> using pkgcore internals.  If they're missing, a fuck ton of other
> things will be breaking long before getting to this specific failure.

Yep, basically what I alluded to on irc. :)

> @Radhermit: I'd suggest just adding a function that does the
> appropriate lookup || die, rather than introducing local assignments
> (which may or may not get dumped out via env saving if invoked in the
> wrong spots).

Hmm, true about the env saving. I was considering doing that (and had the
trivial function done) until I noticed it was only 3 spots ... not "a
lot" imo. :)

I'll revert to that solution since subshell dying works for us now too
so there shouldn't be any issues.

Thanks,
Tim

**Comment by radhermit** [comment]
Done in c00d66.

**Comment by radhermit** [comment]
Now I remembered why I did local assignments originally... because if the file containing the function isn't loaded or is renamed without updating all the uses the code might not error out in some places since it's subshelled. Also, local assignments allow for better error handling and message output in those cases.
