### ISSUE TITLE
pkgcore and binary pkgs?

### ISSUE THREAD

**Issue by joakim-tjernlund** [pkgcore/pkgcore#131]
I am looking for a faster way to merge (and possibly build) binary pkgs.
Is binary packages supported in pkgcore yet? or just functional?

**Comment by radhermit** [comment]
On 2015-09-16 10:02, joakim-tjernlund wrote:
> I am looking for a faster way to merge (and possibly build) binary pkgs.
> Is binary packages supported in pkgcore yet? or just functional?

I'm not sure what you mean by supported vs functional, but merging and
building binpkgs should work as expected in pkgcore. Just specify PKGDIR
in make.conf (probably will move to configuring them in repos.conf at
some point) and add buildpkg or buildsyspkg to FEATURES similar to
portage in order to auto-build binpkgs on merge.

Note that pkgcore doesn't support PORTAGE_BINHOST. Instead of that
support will be added to configure binpkg repos via repos.conf (iirc
there's already another issue open for it).

Also, pmerge supports some of the same options for building/merging
binpkgs, e.g. -b, -k, -K, etc. See the man page or help output for
details.

**Comment by joakim-tjernlund** [comment]
OK, good to know about BINHOST

I am just getting started with pkgcore and I noticed another difference:
emerge -pNDu world
[ebuild   R   ] sys-devel/gcc-4.8.4  USE="cxx nls nptl sanitize -altivec -awt -debug% -doc (-fixed-point) -fortran -gcj -go -graphite (-hardened) (-libssp) -mudflap (-multilib) (-multislot) -nopie -nossp -objc -objc++ -objc-gc -openmp -regression-test -vanilla" 

emerge wants to rebuild gcc as there is a new USE flag, debug, which is default off

Not pmerge though:
pmerge --color false -pNDu @world 
 * Scanning for changed USE...
 * Resolving...
Nothing to merge.

Is this expected?

**Comment by radhermit** [comment]
pmerge's --newuse (-N) support is pretty minimal as it doesn't recurse
on --deep (-D). Support for it needs to move into the resolver or
somewhere else to handle it better, see issue #46, and I've been pushing
that off since the resolver needs a rewrite. :)

**Comment by radhermit** [comment]
Closing this since it's not really about a feature request or bug specifically and related issues should already exist for the discussed missing functionality.

In the future, questions such as this are probably best answered via #pkgcore on freenode or the mailing list which I just noticed should be added to the readme.

**Comment by joakim-tjernlund** [comment]
On Wed, 2015-09-16 at 11:19 -0700, Tim Harder wrote:
> Closing this since it's not really about a feature request or bug specifically and related issues should
> already exist for the discussed missing functionality.
> In the future, questions such as this are probably best answered via #pkgcore on freenode or the mailing 
> list which I just noticed should be added to the readme.

Yes, please. I didn't see a mailing list so I used the issue tracker instead.

**Comment by radhermit** [comment]
On 2015-09-16 15:07, joakim-tjernlund wrote:
> Yes, please. I didn't see a mailing list so I used the issue tracker instead.

I figured as much.

It's now documented on the readme (pkgcore-dev@googlegroups.com) and has
sat dormant for a while but feel free to revive it. :)

**Comment by joakim-tjernlund** [comment]
On Wed, 2015-09-16 at 12:11 -0700, Tim Harder wrote:
> On 2015-09-16 15:07, joakim-tjernlund wrote:
> > Yes, please. I didn't see a mailing list so I used the issue tracker instead.
> 
> I figured as much.
> 
> It's now documented on the readme (pkgcore-dev@googlegroups.com) and has
> sat dormant for a while but feel free to revive it. :)

No wonder I didn't find any list. But please, not google-anything!
Use a github mail list or create one on gentoo.

 Jocke

**Comment by radhermit** [comment]
On 2015-09-16 15:20, joakim-tjernlund wrote:
> No wonder I didn't find any list. But please, not google-anything!
> Use a github mail list or create one on gentoo.

Historically pkgcore was a googlecode project and there aren't any
better options for open source mailing lists that I know of that are
free, 3rd party services.

Also, this isn't an official Gentoo-sanctioned project so I don't think
we can request a mailing list there and keeping a degree of separation
from it is probably for the best at this point.

**Comment by joakim-tjernlund** [comment]
On Wed, 2015-09-16 at 12:32 -0700, Tim Harder wrote:
> On 2015-09-16 15:20, joakim-tjernlund wrote:
> > No wonder I didn't find any list. But please, not google-anything!
> > Use a github mail list or create one on gentoo.
> 
> Historically pkgcore was a googlecode project and there aren't any
> better options for open source mailing lists that I know of that are
> free, 3rd party services.

It isn't any more and having to create yet another account for email will
put off the casual user.

If mail lists isn't possible on github I think it is better to use the issue tracker
instead.

> 
> Also, this isn't an official Gentoo-sanctioned project so I don't think
> we can request a mailing list there and keeping a degree of separation
> from it is probably for the best at this point.

It should become one I think :)

**Comment by radhermit** [comment]
On 2015-09-16 15:48, joakim-tjernlund wrote:
> > Also, this isn't an official Gentoo-sanctioned project so I don't think
> > we can request a mailing list there and keeping a degree of separation
> > from it is probably for the best at this point.

> It should become one I think :)

I don't know about @ferringb, but imo besides providing a mailing list
and perhaps some other infra resources I don't see being an official
project providing any great benefits.

The only way I see things heading that direction would be if portage
does a major rewrite and uses a lot of pkgcore's ideas/code or if
pkgcore ever replaces portage both of which are pretty unlikely right
now.

**Comment by radhermit** [comment]
I should note, I'm somewhat open to hosting some sort of mailing list software and other things on pkgcore.org subdomains, but I'm not overly excited about paying for such stuff out of pocket or the time required to setup/admin the machine.

**Comment by ferringb** [comment]
These days, an official status doesn't provide much.  Pkgcore was external
from gentoo originally to avoid politics, and due to the fact we were using
bzr/git and had our own buildbot infrastructure.  They weren't able to
support our needs at the time (per the norm, they're usually overloaded)
but we could provide it ourselves externally, so we did.

Now, portage and pkgcore both are in github and use travis-ci for CI.  The
only thing that differs for portage and pkgcore is issue tracking and
mailing list- portage can have tickets pass through bugs.g.o, and has a @
gentoo.org mailing list.

I'm not sure how useful that is to be honest.  I think drawing closer to
gentoo upstream is a good notion- going official for example- but the
reality is, that brand doesn't change the day to day development for
pkgcore at all.

If portage and pkgcore were to merge (which I think would be a good notion-
we get portage features, we provide a cleaner underlying architecture),
sure, but that's not happening w/out someone doing a shit ton of leg work.

My 2 cents.  For mailing list, might be worth talking to upstream since
we're something of a special case- that said, it'll probably be a 'no'
since if we get special status everyone has reason to ask for the same.

**Comment by oz123** [comment]
@radhermit 
is there support for this already?

>  Note that pkgcore doesn't support PORTAGE_BINHOST. Instead of that support will be added to configure binpkg repos via repos.conf (iirc there's already another issue open for it).

Can you add an example conf that shows a binary host config?

**Comment by radhermit** [comment]
Nope, the best thing to do would be to track #61 and/or the binpkg branch. I worked on it a while ago, but haven't finished things off. One of the main issues is that it doesn't feel right to shim in binpkg repo support via repos.conf since I assume some people will want the same config file layout to work for both portage and pkgcore (and portage doesn't support configuring binpkg repos like that).

**Comment by oz123** [comment]
@radhermit, how about adding support for binary packages in `binrepos.conf` ? emerge will ignore this, and if emerge developers want, they can add support to it too.
Example usage:
```
 $ ls /etc/portage/repos.conf/
gentoo.conf  local.conf  mate.conf
ls /etc/portage/binrepos.conf/
 binhost1.conf   binhost2.conf
```

**Comment by radhermit** [comment]
I'd rather avoid adding pkgcore specific config files into a portage specific config directory layout. If you're fine with using portage, you can get things working using its existing binpkg support along with PORTAGE_BINHOST, but that doesn't support all the features that I'd like to see.

**Comment by oz123** [comment]
Portage is very messy, and it does not support multiple hosts for binary packages. Improving it is a huge effort, and I would rather use pkgcore for its speed.
