### ISSUE TITLE
Cache regen fails for a number of repos with no clear message

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#262]
See e.g.:
https://qa-reports.gentoo.org/output/repos/booboo.html
https://qa-reports.gentoo.org/output/repos/gamerlay.html
https://qa-reports.gentoo.org/output/repos/gentoo-zh.html
https://qa-reports.gentoo.org/output/repos/jamestr.html
https://qa-reports.gentoo.org/output/repos/lisp.html
https://qa-reports.gentoo.org/output/repos/pentoo.html
https://qa-reports.gentoo.org/output/repos/roslin.html
https://qa-reports.gentoo.org/output/repos/srcshelton.html
https://qa-reports.gentoo.org/output/repos/zugaina.html

I never had a problem like that before, so I'm pretty sure it's a regression.

**Comment by radhermit** [comment]
Yeah, I mentioned there were issues with propagating metadata errors back up during the threaded cache regen since I haven't reworked `pmaint regen` yet since the various metadata error catching work that went in during the past couple years.

Funnily enough, portage appears to generate the cached data with the bad values anyway but I don't think we want to do that in pkgcore.
