### ISSUE TITLE
failglob in cache regen could use a better message

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#277]
```
$ pmaint regen --use-local-desc --pkg-desc-index -t 1 qsx
 * sys-kernel/dracut-049_p20191222: failed sourcing ebuild: returned val from gen_metadata was 'False'
 * Cache regen failed with 1
```

The issue turned out to be a failglob:
```
$ ebuild dracut-049_p20191222.ebuild setup
Appending /tmp/gentoo-overlay to PORTDIR_OVERLAY...
 * dracut-049_p20191222.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                  [ ok ]
/tmp/gentoo-overlay/sys-kernel/dracut/dracut-049_p20191222.ebuild: line 59: no match: README.*
/tmp/gentoo-overlay/sys-kernel/dracut/dracut-049_p20191222.ebuild: line 59: no match: README.*
```

I suppose it would be helpful if that 'no match' was included in the message somewhere.

**Comment by radhermit** [comment]
If I'm recalling correctly, I looked into doing this a year or two ago and it was too annoying to do properly due to how bash handles source command error output combined with how metadata regen was handled. However, this might have been before I IPC-ed die() output which made certain cases of capturing bash errors easier to handle.
