### ISSUE TITLE
pkgcore can't find make.globals when installed by pip

### ISSUE THREAD

**Issue by lucianposton** [pkgcore/pkgcore#278]
```
# pkgcheck show                                                                                                                                               
pkgcheck show: error: parsing failed: failed to load make.global
```

When pkgcore/pkgcheck are installed via pip, pkgcore is unable to find `make.globals`. pip installs to the `/usr/local` prefix by default. Changing pip's prefix to `/usr` fixed the issue.

https://github.com/pkgcore/pkgcore/blob/848c7ba0fb5db46e5d54c2700d1ffbc585deb22b/src/pkgcore/ebuild/portage_conf.py#L125

**Comment by lucianposton** [comment]
This issue occurred on ubuntu 18.04.

I tried in alpine:latest, and pip installed into `/usr` prefix, so pkgcore did not experience this issue there.

I'm not that familiar with pip packaging nor why pip is configured to install to a different prefix on ubuntu, so I'm not sure where this prefix issue ultimately lies.

**Comment by radhermit** [comment]
I'm closing this since it seems like you're running pip with sudo or similar and forcing it to install in system-wide locations. This isn't really what pip is meant for, rather it should generally be used alongside something like virtualenv to install to segregated envs.

Try using pipenv for better encapsulation instead of straight pip if you don't want to mess with virtualenv directly.
