### ISSUE TITLE
pmerge -auDN @world consumes a lot of memory

### ISSUE THREAD

**Issue by dblsaiko** [pkgcore/pkgcore#304]
I tried running the above command for probably at least 3 minutes and it never finished resolving, then I aborted it when it reached 11GB of memory usage. Not sure what information to give so here's the [pconfig dump][1] output, that looks like it has everything in it.

Trying to install single packages is way faster than emerge and also takes a fraction of the memory.

[1]: https://paste.2x.ax/~saiko/df206ac1ddfe191dfce333871a0844ad6f1921d4

**Comment by devurandom** [comment]
I just ran into the same issue. `pmerge` got OOM-killed after locking up the system for a few minutes.

**Comment by ferringb** [comment]
See https://github.com/pkgcore/pkgcore/issues/80#issuecomment-1364810858 ; the underlying issue was a combanitorial explosion for use transitive atoms.  What I've traced, @arthurzam gets the credit for finally fixing that mess- assuming my tracing was correct.

Either way, please re-open if you're still triggering OOMK.  If you are, include the `pconfig dump` and the pmerge invocation so we have a basic understanding of the package graph that triggered it.
