### ISSUE TITLE
Missing support for @INCLUDES_EPREFIX eclassdoc tag

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#404]
`@INCLUDES_EPREFIX` is mentioned in the [devmanual](https://devmanual.gentoo.org/eclass-writing/index.html) and is included in eclass-to-manpage (https://github.com/projg2/eclass-to-manpage/commit/9f9dd280d05922962645f8a14ace3e17df0d82a9) but apparently never made it into pkgcore/pkgcheck?

The tag is to indicate that an eclass variable or eclass function returns a path with `${EPREFIX}` appended.

**Comment by thesamesam** [comment]
cc @mgorny - was there some history here, or just forgot about?

**Comment by ulm** [comment]
Four years later, no eclass uses that tag. Maybe we should revert it in eclass-to-manpage?

Also, it looks a bit like creeping featurism to me (do we also need `@INCLUDES_BROOT` etc.?).

**Comment by arthurzam** [comment]
@ulm @thesamesam I want to verify now, should this be closed as "WONT-DO"?

I myself think this is a good idea to have this "feature", or some other syntax, so we can verify in pkgcheck for simple mistakes (maybe `@INCLUDES_PATH EPREFIX`, `@INCLUDES_PATH BROOT`, or something).
But I leave it to your experienced decision since you have better future vision of such stuff.

**Comment by ulm** [comment]
As I said, it's not used in the tree. Plus, it is only implemented as a stub in `eclass-to-manpage.awk`, which accepts the tag, but does nothing with it.

I'd suggest to revert it in eclass-to-manpage and in the devmanual for now. We can think about adding another solution like `@INCLUDES_PATH` later.

**Comment by thesamesam** [comment]
ulm's suggestion wfm.
